name: test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/repo-checkout@repo
      id: repo
      with:
        manifest_repo: sel4test-manifest
    - env:
        XML: ${{ steps.repo.outputs.xml }}
      run: echo "${XML}"
