# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

# Actions to run on pull requests

name: PR

on: [pull_request]

jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/gitlint@master

  whitespace:
    name: 'Trailing Whitespace'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/git-diff-check@master

  shell:
    name: 'Portable Shell'
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/bashisms@master

  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
    - uses: seL4/ci-actions/style@master

  preprocess:
    name: Preprocess
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, RISCV64]
    steps:
    - uses: seL4/ci-actions/preprocess@master
      with:
        L4V_ARCH: ${{ matrix.arch }}

  cbase:
    needs: preprocess
    if: failure()
    name: 'Proofs (Base)'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, RISCV64]
    steps:
    - uses: actions/cache@v2
      with:
        path: cache/
        # store for each new github.sha, but load from all image caches
        key: ${{ matrix.arch }}-images-cbase-${{ github.sha }}
        key-restore: ${{ matrix.arch }}-images
    - uses: seL4/ci-actions/run-proofs@master
      with:
        session: CBaseRefine
        L4V_ARCH: ${{ matrix.arch }}

  crefine:
    needs: cbase
    name: 'Proofs (C)'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, RISCV64]
    steps:
    - uses: actions/cache@v2
      with:
        path: cache/
        # store for each new github.sha, but load from all image caches
        key: ${{ matrix.arch }}-images-crefine-${{ github.sha }}
        key-restore: ${{ matrix.arch }}-images
    - uses: seL4/ci-actions/run-proofs@master
      with:
        session: CRefine
        L4V_ARCH: ${{ matrix.arch }}
