# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause

name: Preprocess Test

on: [pull_request]

jobs:
  preprocess:
    name: Preprocess
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, ARM_HYP, RISCV64, X64]
    steps:
    - uses: lsf37/ci-actions/preprocess@master
      with:
        L4V_ARCH: ${{ matrix.arch }}
